---
version: '3'

env:
  UBUNTU_VERSION:
    sh: lsb_release -r | awk '{print $2}'

tasks:
  apt:
    desc: Install Apt packages
    cmds:
      - sudo apt install $(cat packages)
  dotfiles:
    desc: Install dotfiles
    cmds:
      - |
        printf "\ninstalling dotfiles ...\n\n"
        for file in $(find $(pwd)/ -name ".*" -not -name ".gitignore" -not -name ".git" -not -name ".config" -not -name ".github" -not -name ".*.swp" -not -name ".gnupg" -not -name "test.sh" -not -name ".bashrc.*" -not -name ".yamllint" -not -name ".pre-commit-config*"); do
            f=$(basename $file);
            echo "$f"
            ln -sfn $file "${HOME}/$f";
        done;
        gpg --list-keys || true;
        mkdir -p "${HOME}/.gnupg";
        for file in $(find $(pwd)/.gnupg); do
            f=$(basename $file);
            ln -sfn $file "${HOME}/.gnupg/$f";
        done;
        mkdir -p "${HOME}/.config/gh";
        ln -snf "$(pwd)/.config/gh/config.yml" "${HOME}/.config/gh/config.yml";
        mkdir -p "${HOME}/.config/micro/syntax/";
        ln -snf "$(pwd)/.config/micro/settings.json" "${HOME}/.config/micro/settings.json";
        ln -snf "$(pwd)/.config/micro/bindings.json" "${HOME}/.config/micro/bindings.json";
        ln -snf "$(pwd)/.config/micro/syntax/sh.yaml" "${HOME}/.config/micro/syntax/sh.yaml";
        git clone "https://github.com/tmux-plugins/tpm" "${HOME}/.tmux/plugins/tpm"
        mkdir -p "${HOME}.config/tmux"
        [ -d "${HOME}/.config/tmux/plugins/catppuccin" ] || mkdir -p "${HOME}/.config/tmux/plugins/catppuccin"
        git clone "https://github.com/catppuccin/tmux.git" "${HOME}/.config/tmux/plugins/catppuccin/tmux"
        ln -snf "$(pwd)/.config/tmux/tmux.conf" "${HOME}/.config/tmux/tmux.conf";
        "${HOME}/.tmux/plugins/tpm/bin/install_plugins"
        TEMP=$(mktemp -d)
        git clone "https://github.com/catppuccin/micro.git" "${TEMP}"
        mkdir -p "${HOME}/.config/micro/colorschemes"
        cp "${TEMP}/src/*" "${HOME}/.config/micro/colorschemes"
        source ~/.bashrc
    silent: true
  import:
    desc: Import brew formulas
    cmds:
      - brew install $(cat formulas)
  export:
    desc: Export brew formulas
    cmds:
      - brew leaves > ./formulas
  venv:
    desc: Run virtual environment
    cmds:
      - echo "/bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/nicholaswilde/dotfiles2/main/scripts/init.sh)\"" | copy
      - docker run -it --rm --entrypoint /bin/bash -u ubuntu -w /home/ubuntu nicholaswilde/ubuntu-server:{{ .UBUNTU_VERSION }}
  init:
    desc: Initialize remote dotfiles
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/nicholaswilde/dotfiles2/main/scripts/init.sh)"
  init-local:
    desc: Initialize local dotfiles
    cmds:
      - ./scripts/init.sh
  serve:
    desc: Serve an mkdocs server
    cmds:
      - mkdocs serve
    silent: true
  shellcheck:
    desc: Shellcheck the repo
    cmds:
      - ./scripts/shellcheck.sh
  default:
    cmds:
      - task -l
    silent: true
