---
version: '3'

env:
  UBUNTU_VERSION:
    sh: lsb_release -r | awk '{print $2}'

tasks:
  dotfiles:
    desc: Install dotfiles
    cmds:
      - |
        printf "\ninstalling dotfiles ...\n\n"
        for file in $(find $(pwd)/ -name ".*" -not -name ".gitignore" -not -name ".git" -not -name ".config" -not -name ".github" -not -name ".*.swp" -not -name ".gnupg" -not -name "test.sh" -not -name ".bashrc.*" -not -name ".yamllint" -not -name ".pre-commit-config*"); do
            f=$(basename $file);
            echo "$f"
            ln -sfn $file "${HOME}/$f";
        done;
        gpg --list-keys || true;
        mkdir -p "${HOME}/.gnupg";
        for file in $(find $(pwd)/.gnupg); do
            f=$(basename $file);
            ln -sfn $file "${HOME}/.gnupg/$f";
        done;
        mkdir -p "${HOME}/.config/gh";
        ln -snf "$(pwd)/.config/gh/config.yml" "${HOME}/.config/gh/config.yml";
        mkdir -p "${HOME}/.config/micro";
        ln -snf "$(pwd)/.config/micro/settings.json" "${HOME}/.config/micro/settings.json";
        ln -snf "$(pwd)/.config/micro/bindings.json" "${HOME}/.config/micro/bindings.json";
        source ~/.bashrc
    silent: true
  venv:
    desc: Run virtual environment
    cmds:
      - echo "/bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/nicholaswilde/dotfiles2/main/scripts/init.sh)\"" | copy
      - docker run -it --rm --entrypoint /bin/bash -u ubuntu -w /home/ubuntu nicholaswilde/ubuntu-server:{{ .UBUNTU_VERSION }}
  init:
    desc: Initialize remote dotfiles
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/nicholaswilde/dotfiles2/main/scripts/init.sh)"
  init-local:
    desc: Initialize local dotfiles
    cmds:
      - ./scripts/init.sh
  default:
    cmds:
      - task -l
    silent: true
